[python]
scan_for_pyfiles = false

[aws]
disabled = true

[docker]
disabled = true

[time]
disabled = false
format = "[$time]($style) "
time_format = '%R'
utc_time_offset = 5.5

[nodejs]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true
