# theme = "dracula"
# icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alert_unit = "GB"
alert = 170
warning = 165
interval = 60
info_type = "available"
format = "{available} free"

# [[block]]
# block = "battery"
# if_command = "test -e /sys/class/power_supply/BAT0"
# interval = 10

[[block]]
block = "cpu"


[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "[%A] %m-%d %H:%M"
[block.icons_overrides]
time = ""


