[[block]]
interval = 60
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "

[[block]]
block = "cpu"
interval = 10
format = " $icon $utilization "

[[block]]
interval = 60
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
interval = 60
block = "battery"
format = " $icon $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"
missing_format = ""

[[block]]
block = "time"
interval = 30
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:fr_BE) "
short = " $icon $timestamp.datetime(f:%R) "