[[block]]
interval = 60
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = "Free: $available "

[[block]]
block = "cpu"
interval = 10
format = " CPU:$utilization "

[[block]]
interval = 60
block = "memory"
format = " RAM:$mem_total_used_percents.eng(w:2) "
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
interval = 60
block = "battery"
format = " BAT:$percentage {$time |} "
device = "DisplayDevice"
driver = "upower"
missing_format = ""

[[block]]
block = "time"
interval = 30
[block.format]
full = " $timestamp.datetime(f:'%a %Y-%m-%d %R %Z') "
short = "%R"
