theme = "dracula"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {available} free"
alert_absolute = true
unit = "GB"
alert = 20
warning = 10
interval = 60

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
interval = 10

[[block]]
block = "cpu"
interval = 10

[[block]]
block = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "time"
interval = 60
format = "[%A] %m-%d %H:%M"
