[[language]]
name = "rust"

# [language.config]
# checkOnSave = { command = "clippy" }

# [[language]]
# name = "python"
# auto-format = false
# [language.formatter]
# command = "black"
# args = [
# "-", # stdin
# "--quiet",
# "--line-length=79",
# ]

[language-server.ruff-lsp]
command = "ruff-lsp"
[[language]]
name = "python"
language-servers = [ "ruff-lsp" ]

# In case you'd like to use ruff alongside black for code formatting:
# formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
