[[language]]
name = "rust"

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]


# [language.config]
# checkOnSave = { command = "clippy" }

# [[language]]
# name = "python"
# auto-format = false
# [language.formatter]
# command = "black"
# args = [
# "-", # stdin
# "--quiet",
# "--line-length=79",
# ]

# [language-server.ruff-lsp]
# command = "ruff-lsp"
# [[language]]
# name = "python"
# scope = "source.python"
# language-servers = [ "ruff-lsp" ]

# In case you'd like to use ruff alongside black for code formatting:
# formatter = { command = "black", args = ["--quiet", "-"] }
# auto-format = true
